version: '3.2'

networks:
  gateway-network:

services:
  iface-mon-ot:
    image: ${REGISTRY:-hub.foundries.io}/iface-monitor:${TAG:-latest}
    tmpfs:
      - /run
      - /var/lock
      - /var/log
    volumes:
      - /var/run/dbus:/var/dbus
    command: "--interface wpan0 --ip \"fd11:22::1/64\" --seconds-delay 10"
    network_mode: "host"
    restart: always
    read_only: true
    privileged: true
    tty: true

  ot-wpantund:
    image: ${REGISTRY:-hub.foundries.io}/ot-wpantund:${TAG:-latest}
    tmpfs:
      - /run
      - /var/lock
      - /var/log
    depends_on:
      - iface-mon-ot
    network_mode: "host"
    restart: always
    read_only: true
    privileged: true

  dns64:
    image: ${REGISTRY:-hub.foundries.io}/dns64:${TAG:-latest}
    tmpfs:
      - /run
      - /var/lock
      - /var/log
      - /var/bind
    network_mode: "host"
    restart: always
    read_only: true

  jool:
    image: ${REGISTRY:-hub.foundries.io}/nat64-jool:${TAG:-latest}
    volumes:
      - /lib/modules:/lib/modules
    network_mode: "host"
    restart: always
    read_only: true
    privileged: true

  californium-proxy:
    image: ${REGISTRY:-hub.foundries.io}/cf-proxy-coap-http:${TAG:-latest}
    read_only: true
    ports:
      - "5682:5682/udp"
    networks:
      - gateway-network
    restart: always
